### ISSUE TITLE
Import stub template failed to serialize

### ISSUE THREAD

**Issue by mvanleijenhorst** [dukeofharen/httplaceholder#267]
Hi Duke of Haren,

I have created a couple of templates and the don't work any more.
Even the example in your Readme.MD doesn't work.

Reproduce steps:
1. Start latest docker container of dukeofharen/httplaceholder:latest
2. Create stub file with template
```json- id: situation-01
  conditions:
    method: GET
    url:
      path:
        equals: /users
      query:
        id:
          equals: 12
        filter:
          equals: first_name
  response:
    statusCode: 200
    text: |
      {
        "first_name": "John"
      }
    headers:
    Content-Type: application/json
```
   
3.  Open httplaceholder application and import.
It will file at the line 'equals: /users'.

If I do the same template with __dukeofharen/httplaceholder:2022.6.11.754__ it works fine.

It looks like every sub element after path failed to parse.

**Comment by dukeofharen** [comment]
@mvanleijenhorst, thanks for your bug report! I tried to reproduce your issue, and (sadly) succeeded in doing it. What I saw, however, is that, because I already had the "latest" version of the HttPlaceholder Docker container on my machine, it uses that version instead of checking if there is a newer "latest" version available.

![image](https://user-images.githubusercontent.com/6454138/188140450-013a8b76-a902-4217-93b3-f0a9a845b09b.png)

The "latest" tag currently points to version "[2022.8.7.27](https://hub.docker.com/layers/dukeofharen/httplaceholder/2022.8.7.27/images/sha256-f65f3209c61dbf4f65b21a9384aee62ba52f3fd040ebee7de9ff404acfca809e?context=explore)". If I put tag "2022.8.7.27" directly in the Docker Compose file, the importing works like a charm. Also, if I delete the image locally by executing `sudo docker image rm dukeofharen/httplaceholder:latest`, it will work again afterwards.

So, I'm curious if you use a version explicitly or delete the image from your machine, if it works again for you. Besides this, I guess it's [not a good idea](https://www.howtogeek.com/devops/understanding-dockers-latest-tag/) to use the `latest` tag if you're deploying any Docker, so perhaps I need to update the documentation to reflect this.

**Comment by mvanleijenhorst** [comment]
@dukeofharen, thanks for the quick response and sorry for my very late reply.

I use the `latest` version instead of a specific version. I removed the `latest` image and pulled it again. And it works like a charm.
The tag `latest` is indeed a little tricky.

**Comment by dukeofharen** [comment]
@mvanleijenhorst yes, no problem. Good luck!
